//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsServices.Models.EntityFrameworkModel
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    [JsonObject(IsReference = true)]
    public partial class Like
    {
        public System.Guid LikeId { get; set; }
        public System.Guid UserRegistrationId { get; set; }
        public System.Guid NewsId { get; set; }
        public Nullable<bool> IsLike { get; set; }
        public Nullable<bool> IsDislike { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }

        public virtual NewsDetail NewsDetail { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }
}
