//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsServices.Models.EntityFrameworkModel
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    [JsonObject(IsReference = true)] 
    public partial class NewsDetail
    {
        public NewsDetail()
        {
            this.Comments = new HashSet<Comment>();
            this.Likes = new HashSet<Like>();
        }
    
        public System.Guid NewsId { get; set; }
        public int CategoryId { get; set; }
        public string NewsPhotoUrl { get; set; }
        public string NewsTitle { get; set; }
        public string NewsDescription { get; set; }
        public Nullable<System.DateTime> CreatedTs { get; set; }
        public System.Guid NewsById { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Like> Likes { get; set; }
    }
}
